#!/bin/bash

virtualenv -p python3 ./venv
./venv/bin/pip install django Pillow mysqlclient pylibmc faker

echo '[client]
database =
user =
password =
default-character-set = utf8
host = 127.0.0.1
port = 3306' > db.cnf
